[package]
name = "minigrep"
version = "0.1.0"
authors = ["JesuÌs Luongo Lizana <jesus.luongo.lizana@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
